FROM arm64v8/gradle:8.4.0-jdk21 AS builder

ARG ACTIVE_PROFILES

RUN mkdir /lutergs-backend
COPY . /lutergs-backend
RUN echo "spring.profiles.active=${ACTIVE_PROFILES}" > /lutergs-backend/src/main/resources/application.properties
WORKDIR /lutergs-backend

RUN gradle bootJar

FROM arm64v8/openjdk:21

WORKDIR /
COPY --from=builder /lutergs-backend/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "-Duser.timezone=Asia/Seoul", "/app.jar"]
