spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:'username'}:${MONGO_PASSWORD:'password'}@${MONGO_URL:'url'}/${MONGO_DATABASE:'db'}?retryWrites=true&w=majority

server:
  port: ${SERVER_PORT:0}

custom:
  db:
    descriptor: ${ORACLE_DESCRIPTOR:'connection-string'}
    username: ${ORACLE_USERNAME:'username'}
    password: ${ORACLE_PASSWORD:'password'}
    max-conn: ${ORACLE_MAX_CONN:3}
    min-conn: ${ORACLE_MIN_CONN:1}

  server:
    url:
      frontend: ${FRONTEND_URL:'frontend-url'}
      frontend-app: ${FRONTEND_PWA_URL:'frontend-pwa-url'}
      backend: ${BACKEND_URL:'backend-url'}
    root-domain: ${ROOT_DOMAIN:localhost}

  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:'access-key'}
      secret-key: ${AWS_SECRET_KEY:'secret-key'}
    region: ap-northeast-2
    s3:
      bucket-name: ${AWS_BUCKET_NAME:'bucket-name'}
      bucket-directory-prefix: ${AWS_BUCKET_PREFIX:'bucket-prefix'}

  oauth:
    client-id: ${OAUTH_CLIENT_ID:'oauth-client-id'}
    client-secret: ${OAUTH_CLIENT_SECRET:'oauth-client-secret'}

  token:
    rsa-key-location: ${RSA_KEY_LOCATION:'./private.pem'}
    expire-hour: ${TOKEN_EXPIRE_HOUR:'2'}
    is-secure: ${ENABLE_SECURE_TOKEN:false}

  push:
    public-key: ${PUSH_PUBLIC_KEY:'push-public-key'}
    private-key: ${PUSH_PRIVATE_KEY:'push-private-key'}
    topic-trigger-key: ${PUSH_TOPIC_TRIGGER_KEY:'push-topic-trigger-key'}
    new-topic:
      request-url: ${PUSH_NEW_TOPIC_REQUEST_URL:'push-new-topic-request-url'}
      username: ${PUSH_NEW_TOPIC_USERNAME:'push-new-topic-username'}
      password: ${PUSH_NEW_TOPIC_PASSWORD:'push-new-topic-password'}
